#!/bin/bash
#SBATCH -N 1
#SBATCH -o test_train.log
#SBATCH --partition=GPU-shared
#SBATCH --ntasks-per-node 8
#SBATCH --gres=gpu:v100-32:4
#SBATCH --time=24:00:00
#SBATCH --dependency=singleton

module load anaconda3
module load cuda
module load cudnn

conda deactivate
conda activate /ocean/projects/ele220002p/tongshen/env/3d
srun ./tools/dist_train.sh configs/sot/vl_tracking/vit_base_patch16.py 4